### ISSUE TITLE
duplicated values when listing listAccountSummaries

### ISSUE THREAD

**Issue by ashhade** [googleapis/java-analytics-admin#436]
https://github.com/googleapis/java-analytics-admin/blob/1de6e558b931da2ad8ca5202fcac835bf96ce2f9/samples/snippets/src/main/java/com/example/analyticsadmin/QuickstartSample.java#L76

currently i'm using the latest version which is 0.12.0 and when i have paging i start see duplicated values when removing the 
`for (AnalyticsAdminServiceClient.ListAccountSummariesPage page : response.iteratePages()) {`
and replace it with 
`for (AccountSummary account : response.iterateAll()) {`
the problem fixed
(the customer have 108 accounts default page size is 50 i start see each property 3 times)

**Comment by ashhade** [comment]
full code 
`   try (AnalyticsAdminServiceClient analyticsAdmin = AnalyticsAdminServiceClient.create(settings)) {

                AnalyticsAdminServiceClient.ListAccountSummariesPagedResponse response =
                        analyticsAdmin.listAccountSummaries(ListAccountSummariesRequest.newBuilder().build());
                for (AnalyticsAdminServiceClient.ListAccountSummariesPage page : response.iteratePages()) {
                    for (AccountSummary account : page.iterateAll()) {
                        for (PropertySummary property : account.getPropertySummariesList()) {`

**Comment by suztomo** [comment]
This repository has moved to googleapis/google-cloud-java. If you still think the issue is valid, would you create an issue there?
